# Generated by Django 2.1.7 on 2019-03-31 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BackupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_hr', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeesUnder_back', to='accounts.Department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employeesWith_back', to='accounts.Designation')),
                ('hr', models.ForeignKey(blank=True, limit_choices_to={'is_hr': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.BackupUser')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_back', to='log.BackupUser')),
            ],
        ),
        migrations.AddField(
            model_name='backup',
            name='from_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_data', to='log.BackupUser'),
        ),
        migrations.AddField(
            model_name='backup',
            name='on_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backup',
            name='to_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_data', to='log.BackupUser'),
        ),
    ]
