# Generated by Django 2.1.7 on 2019-04-02 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('reason', models.CharField(max_length=255)),
                ('eid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
